services:
  - type: web
    name: impqct-clqss
    runtime: static
    staticPublishPath: ./project
    buildCommand: ""
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
